path_prefix: docs
output_dir: build
pages_dir: pages
snippets_dir: snippets
template: docs
templates_dir: ~/dev/repo/nuvola.tiliado.eu/templates
downgrade_headings: yes
title_as_heading: yes
static_dirs:
  - ~/dev/repo/nuvola.tiliado.eu/static
  - images
variables:
  navbar: docs
  nuvola:
    latest:
      version: 4.12.0
      date: July 21th, 2018

